### ISSUE TITLE
FutureWarning: functools.partial usage in miot_device.py causes warning on Python 3.13+

### ISSUE THREAD

**Issue by Bellavista** [rytilahti/python-miio#2034]
Hi,

I’m using the library with Python 3.13 and I’m seeing the following warning during import:

WARNING (ImportExecutor_0) [py.warnings] /usr/local/lib/python3.13/site-packages/miio/miot_device.py:23: FutureWarning: functools.partial will be a method descriptor in future Python versions; wrap it in enum.member() if you want to preserve the old behavior
  Bool = partial(_str2bool)
It looks like the usage of functools.partial in miot_device.py line 23 will no longer work as expected in future Python versions (3.14+).

Would it be possible to update the code to avoid this warning and keep compatibility with future Python versions?

Thanks for your great work on the library!

**Comment by rytilahti** [comment]
Hi, if I don't misrecall, this is already fixed in the git master (and maybe in the 0.6.0 pre-release, which is also available on pypi).

Thanks for the reminder though, that I should definitely create a new release before the 3.14 ships. Alas, I don't currently have neither time nor test devices to do necessary testing..

**Comment by Tasshack** [comment]
Is this going to be fixed or do I need to supress the warning from my project to prevent people to create unnecessary issues on my repo?

**Comment by Xirt** [comment]
According to above comments, this is likely already fixed. My guess is that it did not make it yet to the (formally) distributed version of the library yet, hence everybody is still seeing this error (e.g. in Home Assistant). The last release of this library was in 2022 and [rytilahti](https://github.com/rytilahti) indicated he has limited time to prep a new release (although things might have changed in the meantime).
